name: weaving
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - flake8
    - wheel
    - jupyterlab==3.3.4 
    - ipykernel==5.5.5 
    - ipywidgets==7.7.2 
    - jupyterlab-widgets==1.1.1
    - networkx
    - matplotlib
    - numpy
    - scipy
  - pytest
  - pytest-html
  - pytest-timeout
